version: '3'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    links:
      #- mysql
      - postgres
      #- mail
      #- solr
      #- elasticsearch
      #- redis
      #- memcached
      #- ftp
    ports:
      - "8000:80"
      - "8443:443"
      - "10022:22"
    volumes:
      - ./app/:/app/
    env_file:
      - etc/environment.yml
      - etc/environment.production.yml

      #######################################
      # MySQL server
      #######################################
      #mysql:
      #  build:
      #    context: docker/mysql/
      #dockerfile: MySQL-5.5.Dockerfile
      #    dockerfile: MySQL-5.6.Dockerfile
      #dockerfile: MySQL-5.7.Dockerfile
      #dockerfile: MariaDB-5.5.Dockerfile
      #dockerfile: MariaDB-10.Dockerfile
      #dockerfile: Percona-5.5.Dockerfile
      #dockerfile: Percona-5.6.Dockerfile
      #dockerfile: Percona-5.7.Dockerfile
  #  volumes:
  #    - mysql:/var/lib/mysql
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.production.yml

  #######################################
  # PostgreSQL server
  #######################################
  postgres:
    build:
      context: docker/postgres/
      dockerfile: Postgres-9.4.Dockerfile
    #    dockerfile: Postgres-9.5.Dockerfile
    ports:
      - 15432:5432
    #volumes:
    #  - solr:/opt/solr/server/solr/data
    env_file:
      - etc/environment.yml
      - etc/environment.production.yml

    #######################################
    # Solr server
    #######################################
    #solr:
    #  build:
    #    context: docker/solr/
    #  ports:
    #    - 18983:8983
    #  volumes:
    #    - solr:/opt/solr/server/solr/data
    #  environment:
    #    - SOLR_STORAGE=/opt/solr/server/solr/data
    #  env_file:
    #    - etc/environment.yml
    #    - etc/environment.production.yml

    #######################################
    # Elasticsearch
    #######################################
    #elasticsearch:
    #  build:
    #    context: docker/elasticsearch/
    #  ports:
    #    - 19200:9200
    #    - 19300:9300
    #  volumes:
    #    - elasticsearch:/usr/share/elasticsearch/data
    #  env_file:
    #    - etc/environment.yml
    #    - etc/environment.production.yml

    #######################################
    # Redis
    #######################################
    #redis:
    #  build:
    #    context: docker/redis/
    #  volumes:
    #    - redis:/data
    #  env_file:
    #    - etc/environment.yml
    #    - etc/environment.production.yml

    #######################################
    # Memcached
    #######################################
    #memcached:
    #  build:
    #    context: docker/memcached/
    #  env_file:
    #    - etc/environment.yml
    #    - etc/environment.production.yml

    #######################################
    # FTP (vsftpd)
    #######################################
    #ftp:
    #  build:
    #    context: docker/vsftpd/
    #  volumes:
    #    - ./:/application/
    #  env_file:
    #    - etc/environment.yml
    #    - etc/environment.production.yml
  #######################################
  # pgAdmin
  #######################################
  pgAdmin:
    depends_on:
      - postgres
    links:
      - postgres
    restart: always
    container_name: "pgadmin4"
    image: dpage/pgadmin4
    ports:
      - "9000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: atef.ouerghi@spa-rac.org
      PGADMIN_DEFAULT_PASSWORD: toufa_2512
    volumes:
      - pgadmin:/var/lib/pgadmin
  #######################################
  # Portainer
  #######################################
  portainer:
    image: portainer/portainer
    container_name: "MAMIAS_portainer"
    restart: always
    ports:
      - "9001:80"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  #mysql:
  postgres:
  pgadmin:
  #solr:
  #elasticsearch:
  #redis:
  #phpmyadmin:
