<?php

return [
	Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
	Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
	Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
	Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
	Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
	Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
	Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
	Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
	Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
	Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
	Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
	FM\ElfinderBundle\FMElfinderBundle::class => ['all' => true],
	Vich\UploaderBundle\VichUploaderBundle::class => ['all' => true],
	WhiteOctober\BreadcrumbsBundle\WhiteOctoberBreadcrumbsBundle::class => ['all' => true],
	App\Application\Sonata\UserBundle\ApplicationSonataUserBundle::class => ['all' => true],
	App\Application\Sonata\ClassificationBundle\ApplicationSonataClassificationBundle::class => ['all' => true],
	App\Application\Sonata\NewsBundle\ApplicationSonataNewsBundle::class => ['all' => true],
	App\Application\Sonata\MediaBundle\ApplicationSonataMediaBundle::class => ['all' => true],
	Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
	Orbitale\Bundle\CmsBundle\OrbitaleCmsBundle::class => ['all' => true],
	Sonata\EasyExtendsBundle\SonataEasyExtendsBundle::class => ['all' => true],
	Sonata\DatagridBundle\SonataDatagridBundle::class => ['all' => true],
	Sonata\CoreBundle\SonataCoreBundle::class => ['all' => true],
	Sonata\BlockBundle\SonataBlockBundle::class => ['all' => true],
	Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
	Sonata\AdminBundle\SonataAdminBundle::class => ['all' => true],
	FOS\UserBundle\FOSUserBundle::class => ['all' => true],
	Sonata\UserBundle\SonataUserBundle::class => ['all' => true],
	Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle::class => ['all' => true],
	Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
	JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
	Sonata\MediaBundle\SonataMediaBundle::class => ['all' => true],
	Sonata\IntlBundle\SonataIntlBundle::class => ['all' => true],
	Knp\Bundle\MarkdownBundle\KnpMarkdownBundle::class => ['all' => true],
	FOS\CKEditorBundle\FOSCKEditorBundle::class => ['all' => true],
	Sonata\FormatterBundle\SonataFormatterBundle::class => ['all' => true],
	Sonata\ClassificationBundle\SonataClassificationBundle::class => ['all' => true],
	Sonata\NewsBundle\SonataNewsBundle::class => ['all' => true],
	SymfonyCasts\Bundle\ResetPassword\SymfonyCastsResetPasswordBundle::class => ['all' => true],
	Sonata\CacheBundle\SonataCacheBundle::class => ['all' => true],
	Sonata\TranslationBundle\SonataTranslationBundle::class => ['all' => true],
	RedCode\TreeBundle\RedCodeTreeBundle::class => ['all' => true],
	Ob\HighchartsBundle\ObHighchartsBundle::class => ['all' => true],
	Picoss\SonataExtraAdminBundle\PicossSonataExtraAdminBundle::class => ['all' => true],
	PUGX\AutocompleterBundle\PUGXAutocompleterBundle::class => ['all' => true],
	EWZ\Bundle\RecaptchaBundle\EWZRecaptchaBundle::class => ['all' => true],
	Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
	Liip\ImagineBundle\LiipImagineBundle::class => ['all' => true],
	Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
	ApiPlatform\Core\Bridge\Symfony\Bundle\ApiPlatformBundle::class => ['all' => true],
];
