<?php

namespace App\Form;

use App\Entity\Country;
use App\Entity\SearchCountry;
use App\Repository\CountryRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CountrySearchType extends AbstractType
{
	public function buildForm (FormBuilderInterface $builder, array $options)
	{
		$builder
			->add (
				'country',
				EntityType::class,
				[
					'class' => Country::class,
					'query_builder' => function (CountryRepository $er) {
						return $er->createQueryBuilder ('f')
							->orderBy ('f.country', 'ASC');
					},
					'placeholder' => 'Select A country',
					'choice_label' => 'country',
					'choice_value' => 'id',
					'attr' => ['class' => 'form-control select2'],
					'required' => false
				]
			);
	}

	public function configureOptions (OptionsResolver $resolver)
	{
		$resolver->setDefaults (
			[
				'data_class' => SearchCountry::class,
				'methode' => 'get',
				'csrf_protection' => false,
				'validation_groups' => false,
			]
		);
	}

	public function getBlockPrefix ()
	{
		return ''; // TODO: Change the autogenerated stub
	}
}
