api_platform:
    title: 'MAMIAS WebService'
    description: 'The MAMIAS RESTful Web Service enables users to extract species information from the MAMIAS Catalogue.'
    version: '1.0.0'
    #showWebby: false
    enable_nelmio_api_doc: False
    # Enable the Swagger documentation and export.
    enable_swagger: true
    # Enable Swagger ui.
    enable_swagger_ui: true
    swagger:
        # The active versions of OpenAPI to be exported or used in the swagger_ui. The first value is the default.
        versions: [3]

        # The swagger api keys.
        api_keys: []
        # The name of the header or query parameter containing the api key.
        # name: ''

        # Whether the api key should be a query parameter or a header.
        # type: 'query' or 'header'
    #collection:
    #    pagination:
    #        client_enabled: true
    #        enabled_parameter_name: pagination # optional
    collection:
        order_parameter_name:          'order'
        order:                         'ASC'
        #pagination:
        #page_parameter_name:      _page
        #client_enabled:            true
        #client_items_per_page:     true
    # Enable the entrypoint.
    enable_entrypoint: true
    # Enable the docs.
    enable_docs: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
        #csv:
        #    mime_types: ['text/csv']

