sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.block.service.text:
        sonata.block.service.rss:
        #sonata.timeline.block.timeline:
        sonata.user.block.menu:
            contexts: [admin]    # used to display the menu in profile pages
        #sonata.user.block.account: # used to display menu option (login option)
        # MediaBundle's Blocks
        sonata.media.block.media:
        sonata.media.block.gallery:
        sonata.media.block.feature_media:
        sonata.formatter.block.formatter:
        #sonata:news:block:recent_posts:

sonata_admin:
    title: 'Mamias Admin'
    #title_logo: bundles/sonataadmin/logo_title.png
    search: false
    options:
        html5_validate: true
        # Auto order groups and admins by label or id
        sort_admins: false
        confirm_exit: true
        use_select2: true
        use_icheck: true
        use_bootlint: false
        use_stickyforms: true
        #pager_links: null
        form_type: standard
        dropdown_number_groups_per_colums:  2
        title_mode: single_text # One of "single_text"; "single_image"; "both"
        # Enable locking when editing an object, if the corresponding object manager supports it.
        lock_protection: true
    show_mosaic_button: false
    persist_filters: true
    security:
        handler:              sonata.admin.security.handler.noop

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
        #role_s : ROLE_S


    templates:
        layout:                         'standard_layout.html.twig'
        ajax:                           '@SonataAdmin/ajax_layout.html.twig'
        list:                           '@SonataAdmin/CRUD/list.html.twig'
        show:                           '@SonataAdmin/CRUD/show.html.twig'
        show_compare:                   '@SonataAdmin/CRUD/show_compare.html.twig'
        edit:                           '@SonataAdmin/CRUD/edit.html.twig'
        history:                        '@SonataAdmin/CRUD/history.html.twig'
        preview:                        '@SonataAdmin/CRUD/preview.html.twig'
        delete:                         '@SonataAdmin/CRUD/delete.html.twig'
        batch:                          '@SonataAdmin/CRUD/list__batch.html.twig'
        acl:                            '@SonataAdmin/CRUD/acl.html.twig'
        action:                         '@SonataAdmin/CRUD/action.html.twig'
        select:                         '@SonataAdmin/CRUD/list__select.html.twig'
        filter:                         '@SonataAdmin/Form/filter_admin_fields.html.twig'
        dashboard:                      '@SonataAdmin/Core/dashboard.html.twig'
        search:                         '@SonataAdmin/Core/search.html.twig'
        batch_confirmation:             '@SonataAdmin/CRUD/batch_confirmation.html.twig'
        inner_list_row:                 '@SonataAdmin/CRUD/list_inner_row.html.twig'
        base_list_field:                '@SonataAdmin/CRUD/base_list_field.html.twig'
        list_block:                     '@SonataAdmin/Block/block_admin_list.html.twig'
        user_block:                     'user_block.html.twig'
        add_block:                      '@SonataAdmin/Core/add_block.html.twig'
        pager_links:                    '@SonataAdmin/Pager/links.html.twig'
        pager_results:                  '@SonataAdmin/Pager/results.html.twig'
        tab_menu_template:              '@SonataAdmin/Core/tab_menu_template.html.twig'
        history_revision_timestamp:     '@SonataAdmin/CRUD/history_revision_timestamp.html.twig'
        short_object_description:       '@SonataAdmin/Helper/short-object-description.html.twig'
        search_result_block:            '@SonataAdmin/Block/block_search_result.html.twig'
        action_create:                  '@SonataAdmin/CRUD/dashboard__action_create.html.twig'
        button_acl:                     '@SonataAdmin/Button/acl_button.html.twig'
        button_create:                  '@SonataAdmin/Button/create_button.html.twig'
        button_edit:                    '@SonataAdmin/Button/edit_button.html.twig'
        button_history:                 '@SonataAdmin/Button/history_button.html.twig'
        button_list:                    '@SonataAdmin/Button/list_button.html.twig'
        button_show:                    '@SonataAdmin/Button/show_button.html.twig'

    assets:
        stylesheets:

            # The default stylesheet list:
            - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
            - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
            - assets/css/AdminLTE.css
            - assets/css/skin-blue.css
            - bundles/sonataadmin/vendor/iCheck/skins/square/blue.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonatacore/vendor/select2/select2.css
            - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonataadmin/css/tree.css
            - bundles/sonataadmin/css/colors.css

        extra_javascripts:
            # ...
            - bundles/fosckeditor/ckeditor.js
            - bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
            - bundles/sonataformatter/markitup/sets/markdown/set.js
            - bundles/sonataformatter/markitup/sets/html/set.js
            - bundles/sonataformatter/markitup/sets/textile/set.js

        extra_stylesheets:
            # ...
            - bundles/sonataformatter/markitup/skins/sonata/style.css
            - bundles/sonataformatter/markitup/sets/markdown/style.css
            - bundles/sonataformatter/markitup/sets/html/style.css
            - bundles/sonataformatter/markitup/sets/textile/style.css
    dashboard:
        blocks:

            -   position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [sonata.admin.group.classification, News, CMS, User]
            #-   position: left
            #    type: sonata.timeline.block.timeline
            #    settings:
            #        context: {SONATA_ADMIN, max_per_page: 10}
            #        icon: '<i class="fa fa-flag-o fa-fw"></i>'

            -   position: center
                type: sonata.block.service.text
                settings:
                    content: >

                        <div class="box box-primary">
                          <div class="box-header with-border">
                            <h3 class="box-title">Welcome to the MAMIAS </h3>
                          </div>
                          <div class="box-body">
                            Marine Mediterranean Invasive Alien Species Database Since 2012.
                            The Database includes among Alien species ,cryptogenic ones. Tropical Atlantic species, which have expanded their geographic distribution in the Mediterranean, are noted as range expansion, or vagrant.
                            The Database includes also species that have been occasionally reported as alien but were subsequently excluded from lists, along with the reasoning of their exclusion.
                          </div>
                        </div>

            -   position: center
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Mamias, Literrature]

            -   position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Settings]


        groups:
            Mamias:
                label:           Mamias Plateform
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa  fa-database"></i>'
                items:
                    - admin.catalogue
                    - admin.mamias
                    - admin.pathway
                    - admin.country_distribution
                    - admin.geo_occurence
                roles: ['ROLE_SUPER_ADMIN','ROLE_ADMIN', 'ROLE_SONATA_ADMIN', 'ROLE_S']

            Literrature:
                label:           Mamias Literature
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-book"></i>'
                items:
                    - admin.literature
                roles: ['ROLE_SUPER_ADMIN','ROLE_ADMIN', 'ROLE_SONATA_ADMIN', 'ROLE_S']

            News:
                label:           News
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-newspaper-o"></i>'
                items:
                    - sonata.classification.admin.collection
                    - sonata.news.admin.post
                roles: ['ROLE_SUPER_ADMIN','ROLE_ADMIN', 'ROLE_SONATA_ADMIN']

            CMS:
                label:           CMS
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-file-text-o"></i>'
                items:
                    - admin.category
                    - admin.page
                roles: ['ROLE_SUPER_ADMIN','ROLE_ADMIN', 'ROLE_SONATA_ADMIN']

            Settings:
                label:           MAMIAS Settings
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa  fa-gears"></i>'
                items:
                    - admin.ecofunctional
                    - admin.status
                    - admin.success_type
                    - admin.invasiveness
                    - admin.origin
                    - admin.vectors
                    - admin.vector_name
                    - admin.country
                    - admin.ec_ap
                    - admin.regional_sea
                roles: ['ROLE_SUPER_ADMIN','ROLE_ADMIN', 'ROLE_SONATA_ADMIN']

            User:
                label:           User Management
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-users"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                roles: ['ROLE_SUPER_ADMIN','ROLE_ADMIN', 'ROLE_SONATA_ADMIN']
